name: ptm-ci
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  basic-suite:
    runs-on: ubuntu-18.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y make gfortran gcc g++
        sudo apt-get install -y python3-pip python3-setuptools python3-wheel
        pip3 install numpy scipy matplotlib
        pip3 install spacepy
        pip3 freeze
        gfortran --version
    - name: Checkout
      uses: actions/checkout@v2
    - name: build-ptm
      run: |
        make ptm
        ./ptm 1
    - name: test-dipole
      run: |
        make clean
        make ptm
        python3 setup.py install --user
        python3 ptm_python/ptm_test_data.py
